[rule.context-keys-type]
[rule.time-equal]
[rule.time-naming]
[rule.var-declaration]
[rule.unexported-return]
[rule.errorf]
[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
# [rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
# [rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
# [rule.file-header]
[rule.empty-block]
[rule.superfluous-else]
[rule.get-return]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.unnecessary-stmt]
[rule.struct-tag]
[rule.modifies-value-receiver]
[rule.constant-logical-expr]
[rule.bool-literal-in-expr]
[rule.redefines-builtin-id]
[rule.imports-blacklist]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.waitgroup-by-value]
[rule.atomic]
[rule.empty-lines]
[rule.duplicated-imports]
[rule.import-shadowing]
[rule.bare-return]
[rule.unused-receiver]
[rule.unhandled-error]
[rule.string-of-int]
# [rule.string-format]
[rule.early-return]
[rule.unconditional-recursion]
[rule.identical-branches]
[rule.defer]
[rule.unexported-naming]
[rule.useless-break]
[rule.optimize-operands-order]
# [rule.use-any]
# [rule.datarace]
